Repository codestates-seb/seb43_main_011, pull requests merged in 2023-05, with the labels that each got.

#6 Feat : CustomBookmark/Recipe Entity 구현
  be/cocktail/src/main/java/com/BE/cocktail/customBookmark/CustomBookmark.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipe.java
Labels: documentation

#35 Feat : RegularRecipe Api 작업환경 구성
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeRepository.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeService.java
Labels: BE, Feat

#36 Feat : mySql 환경 세팅
  be/cocktail/src/main/resources/application.yml
Labels: BE, Feat

#37 Feat : CustomRecipe API 환경구성
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeRepository.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeService.java
Labels: BE, Feat

#39 Feat: LoginPage, DetailPage 레이아웃 잡기
  fe/src/App.tsx
  fe/src/components/header/Header.tsx
  fe/src/images/login.png
  fe/src/images/login1.png
  fe/src/images/loginLogo.png
  fe/src/images/logo-whigte.png
  fe/src/pages/DetailPage.tsx
  fe/src/pages/LoginPage.tsx
Labels: Feat, FE

#41 Feat : customRecipe submit,findAll 구현
  be/cocktail/build.gradle
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipe.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeService.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/dto/CustomRecipePostDto.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/dto/CustomRecipeResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/dto/CustomRecipeResponseDtoList.java
  be/cocktail/src/main/java/com/BE/cocktail/ingredient/Ingredient.java
  be/cocktail/src/main/java/com/BE/cocktail/member/Member.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipe.java
  be/cocktail/src/main/resources/application.yml
Labels: BE, Feat

#42 Feat : ApiResponse 구현
  be/cocktail/src/main/java/com/BE/cocktail/apiResponse/ApiResponse.java
  be/cocktail/src/main/java/com/BE/cocktail/apiResponse/CocktailRtnConsts.java
  be/cocktail/src/main/java/com/BE/cocktail/apiResponse/CocktailRtnGrp.java
Labels: BE, Feat

#43 Feat : 정규레시피 상세조회 API 구현
  be/cocktail/src/main/java/com/BE/cocktail/ingredient/IngredientResponses.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipe.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeRepository.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeService.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/RegularRecipeCreateDto.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/RegularRecipeCreateResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/RegularRecipeSingleResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/SingleResponse.java
Labels: BE, Feat

#44 Feat : Exception Handler 구현
  be/cocktail/src/main/java/com/BE/cocktail/exception/CocktailException.java
  be/cocktail/src/main/java/com/BE/cocktail/exception/GlobalExceptionHandler.java
Labels: BE, Feat

#45 Feat : securityConfig 구현
  be/cocktail/src/main/java/com/BE/cocktail/auth/SecurityConfig.java
Labels: BE, Feat

#46 Feat : 회원레시피, 정규레시피, 재료에 status 컬럼추가
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipe.java
  be/cocktail/src/main/java/com/BE/cocktail/ingredient/Ingredient.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipe.java
Labels: BE, Feat

#47 feat: SignUp페이지유효성검사기능추가- style: SignUp페이지스타일추가 및 변경- style: 레시피등록페이지…
  .DS_Store
  fe/src/App.tsx
  fe/src/images/error.jpg
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/Error.tsx
  fe/src/pages/Signup.tsx
Labels: Feat, FE

#49 Refactor : 정규레시피 생성 과정 리팩토링
  be/cocktail/src/main/java/com/BE/cocktail/ingredient/IngredientRequest.java
  be/cocktail/src/main/java/com/BE/cocktail/ingredient/IngredientResponses.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipe.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeService.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/RegularRecipeCreateDto.java
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/RegularRecipeCreateResponseDto.java
Labels: BE, Refactor

#48 Feat: nav bar 레이아웃 변경 및 card, button click 애니메이션 구현, recipeList Ajax 요청 구현, json-server 추가
  .DS_Store
  fe/data.json
  fe/src/App.tsx
  fe/src/components/NavBar/NavBar.tsx
  fe/src/components/card/Card.tsx
  fe/src/components/card/CardList.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/header/NavController.tsx
  fe/src/components/sideBar/SideBar.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/Main.tsx
  fe/src/redux/slices/RecipeSlice.ts
  fe/src/redux/slices/SideView.ts
  fe/src/redux/slices/isNavOpenSlice.ts
  fe/src/redux/store.ts
Labels: Feat, FE

#51 Feat : LoginPage 기능, 유효성검사 추가
  fe/src/pages/LoginPage.tsx
  fe/src/redux/slices/UserSlice.ts
  fe/src/redux/store.ts
Labels: Feat, FE

#53 Feat : 레시피 검색 기능
  fe/data.json
  fe/src/App.tsx
  fe/src/components/card/Card.tsx
  fe/src/components/card/CardList.tsx
  fe/src/components/header/Header.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/Main.tsx
  fe/src/redux/slices/RecipeSlice.ts
Labels: Feat, FE, Refactor

#55 Refactor : RegularRecipe DB 저장 코드 변경
  be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeService.java
Labels: BE, Refactor

#57 Feat : 이미지 업로드 전 미리보기 및 검색 결과 페이지 스타일 수정
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/Main.tsx
Labels: Feat, FE

#59 Refactor : 페이지 분리 및 애니메이션, type 이름 변경
  fe/src/App.tsx
  fe/src/components/card/Card.tsx
  fe/src/components/card/CardList.tsx
  fe/src/pages/CustomRecipes.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/SearchResults.tsx
  fe/src/redux/slices/RecipeSlice.ts
Labels: FE, Refactor

#60 Refactor : react-query 추가 및 api 요청 변경
  fe/package-lock.json
  fe/package.json
  fe/src/components/NavBar/NavBar.tsx
  fe/src/components/card/CardList.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/header/NavController.tsx
  fe/src/index.tsx
  fe/src/pages/CustomRecipes.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/SearchResults.tsx
  fe/src/redux/slices/NavSlice.ts
  fe/src/redux/slices/RecipeSlice.ts
  fe/src/redux/store.ts
  fe/src/utils/query.ts
Labels: FE, Refactor

#61 Refactor : customRecipe api 주소변경과 entity변경에 따른 코드 수정, Bookmark 엔티티 class 삭제
  be/cocktail/src/main/java/com/BE/cocktail/customBookmark/CustomBookmark.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipe.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeRepository.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeService.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/dto/CustomPatchDto.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/dto/CustomRecipePostDto.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/dto/CustomRecipeResponseDtoList.java
  be/cocktail/src/main/java/com/BE/cocktail/regularBookmark/RegularBookmark.java
Labels: BE, Refactor

#62 Feat : CuntomRecipe 삭제 응답메세지추가, CuntomRecipeController에 ApiResponse로 형변환
  be/cocktail/src/main/java/com/BE/cocktail/apiResponse/CocktailRtnConsts.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeService.java
Labels: BE, Feat

#63 Feat: 등록페이지작성데이터서버전송기능- Remove: 자동완성기능삭제
  fe/data.json
  fe/db.json
  fe/package-lock.json
  fe/package.json
  fe/src/index.tsx
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/DetailPage.tsx
Labels: Feat, FE, Refactor

#64 Refactor : 정규레시피 상세조회 API 리팩토링
  be/cocktail/src/main/java/com/BE/cocktail/controller/regularRecipe/RegularRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/apiResponse/CocktailRtnConsts.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/apiResponse/CocktailRtnGrp.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeCreateDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeGetResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeSingleResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/utils/SingleResponse.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/customRecipe/CustomRecipe.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/member/Member.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/regularRecipe/RegularRecipe.java
  be/cocktail/src/main/java/com/BE/cocktail/service/regularRecipe/RegularRecipeService.java
  be/cocktail/src/main/resources/application.yml
  be/cocktail/src/main/resources/ddl/ddl.sql
  be/cocktail/src/main/resources/dml/dml.sql
Labels: BE, Refactor

#67 Feat : 정규레시피 페이징 기능 구현
  be/cocktail/src/main/java/com/BE/cocktail/controller/customeRecipe/CustomRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/utils/MultiResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/utils/PageInfo.java
  be/cocktail/src/main/java/com/BE/cocktail/service/customRecipe/CustomRecipeService.java
Labels: BE, Feat

#68 Feat : 커스텀레시피 검색기능 구현
  be/cocktail/src/main/java/com/BE/cocktail/controller/customeRecipe/CustomRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomSearchResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/repository/customRecipe/CustomRecipeRepository.java
  be/cocktail/src/main/java/com/BE/cocktail/service/customRecipe/CustomRecipeService.java
Labels: BE, Feat

#66 Refactor : api 변경에 따른 코드 수정
  fe/data.json
  fe/src/components/card/CardList.tsx
  fe/src/components/card/SearchResultsTab.tsx
  fe/src/components/card/SearchedRecipe.tsx
  fe/src/pages/CustomRecipes.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/SearchResults.tsx
  fe/src/utils/query.ts
Labels: FE, Refactor

#69 Feat : 정규레시피 검색기능 구현
  be/cocktail/src/main/java/com/BE/cocktail/controller/regularRecipe/RegularRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularSearchResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/repository/regularRecipe/RegularRecipeRepository.java
  be/cocktail/src/main/java/com/BE/cocktail/service/regularRecipe/RegularRecipeService.java
Labels: BE, Feat

#70 Style : findbyKeyword 메서드명 오타수정
  be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/MultiResponse.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/repository/customRecipe/CustomRecipeRepository.java
  be/cocktail/src/main/java/com/BE/cocktail/service/customRecipe/CustomRecipeService.java
Labels: documentation, BE

#74 Refactor : data.json db.json 통합 및 api호출 주소 변경
  fe/data.json
  fe/db.json
  fe/src/App.tsx
  fe/src/components/card/Card.tsx
  fe/src/components/card/CardList.tsx
  fe/src/components/card/SearchedRecipe.tsx
  fe/src/data.json
  fe/src/index.tsx
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/CustomRecipes.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/SearchResults.tsx
  fe/src/utils/query.ts
Labels: FE, Refactor

#75 Design: 회원가입페이지를 로그인화면으로 디자인- Refactor: 사용하지않는 컴포넌트 삭제
  fe/package-lock.json
  fe/package.json
  fe/src/images/enter1.jpg
  fe/src/images/enter2.jpg
  fe/src/images/enter3.jpg
  fe/src/index.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/Signup.tsx
Labels: FE, Refactor

#78 Refactor: GoogleSignIn컴포넌트화 - Rename: Signup페이지 SignIn으로 이름수정
  fe/src/App.tsx
  fe/src/components/loginbutton/GoogleSignIn.tsx
  fe/src/images/signupImage.jpg
  fe/src/images/signupImage2.jpg
  fe/src/images/signupImage3.jpg
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/SignIn.tsx
Labels: FE, Refactor

#79 Feat: Mypage 레이아웃 잡기
  fe/src/App.tsx
  fe/src/components/myPage/MenuBar.tsx
  fe/src/components/myPage/MyInfo.tsx
  fe/src/pages/Mypage.tsx
Labels: Feat, FE

#81 Refactor : type 이름 변경 및 axios baseURL 추가
  fe/data.json
  fe/src/components/card/SearchResultsTab.tsx
  fe/src/components/card/SearchedRecipe.tsx
  fe/src/pages/SearchResults.tsx
  fe/src/utils/query.ts
Labels: FE, Refactor

#85 Feat : Jwt 설정
  be/cocktail/build.gradle
  be/cocktail/src/main/java/com/BE/cocktail/auth/CustomAuthorityUtils.java
  be/cocktail/src/main/java/com/BE/cocktail/auth/MemberDetailsService.java
  be/cocktail/src/main/java/com/BE/cocktail/auth/SecurityConfig.java
  be/cocktail/src/main/java/com/BE/cocktail/auth/jwt/JwtAuthenticationFilter.java
  be/cocktail/src/main/java/com/BE/cocktail/auth/jwt/JwtTokenizer.java
  be/cocktail/src/main/java/com/BE/cocktail/auth/jwt/JwtVerificationFilter.java
  be/cocktail/src/main/java/com/BE/cocktail/controller/member/MemberController.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/LoginDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/apiResponse/ApiResponse.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/member/SignUpDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeMultiResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/customRecipe/CustomRecipe.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/member/Member.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/repository/member/MemberRepository.java
  be/cocktail/src/main/java/com/BE/cocktail/service/customRecipe/CustomRecipeService.java
  be/cocktail/src/main/java/com/BE/cocktail/service/member/MemberService.java
  be/cocktail/src/main/java/com/BE/cocktail/utils/GetAuthUserUtils.java
  be/cocktail/src/main/resources/application.yml
Labels: BE, Feat

#83 Refactor: PhotoArea사이즈 조정 - Design: Recipe,Ingredient 스크롤바 추가
  fe/data.json
  fe/src/pages/DetailPage.tsx
Labels: FE, Refactor

#86 Feat: Logo Link기능 추가
  fe/src/components/loginbutton/GoogleSignIn.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/SignIn.tsx
  fe/src/pages/SignUp.tsx
Labels: Feat, FE

#82 Feat: 이미지업로드기능추가- Refactor: 이미지업로드형식변경
  fe/data.json
  fe/src/pages/CocktailRegistration.tsx
Labels: Feat, FE, Refactor

#89 Refactor: api서버요청방식react-query적용 및 초기값설정변경- Design: 디자인변경
  fe/package-lock.json
  fe/package.json
  fe/src/pages/CocktailRegistration.tsx
Labels: FE, Refactor

#92 Refactor : SecurityConfig 설정 변경, Memeber 상세조회 dto 추가
  be/cocktail/src/main/java/com/BE/cocktail/auth/SecurityConfig.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/member/MemberInfoResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/MultiResponse.java
Labels: BE, Refactor

#91 Refactor: 이미지업로드폼 컴포넌트분리
  fe/src/components/imageupload/ImageUpload.tsx
  fe/src/pages/CocktailRegistration.tsx
Labels: FE, Refactor

#93 Refactor : 레시피 목록 조회 백엔드 api 적용
  fe/package.json
  fe/src/components/card/Card.tsx
  fe/src/components/card/CardList.tsx
  fe/src/components/card/RecipePagination.tsx
  fe/src/components/card/SearchedRecipe.tsx
  fe/src/pages/CustomRecipes.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/SearchResults.tsx
  fe/src/utils/query.ts
Labels: FE, Refactor

#94 Refactor: DatailPage 커스텀훅 생성 및 수정
  fe/src/App.tsx
  fe/src/components/myPage/MyInfo.tsx
  fe/src/hooks/useFetchRecipe.tsx
  fe/src/pages/DetailPage.tsx
Labels: FE, Refactor

#95 Refactor: CocktailRegistration페이지 서버로 전송할 재료 데이터 및 재료입력 폼 로직 수정
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/LoginPage.tsx
Labels: FE, Refactor

#98 Feat: MyInfo컴포넌트 레이아웃 변경 및 react-query적용
  fe/src/components/myPage/EditMyInfo.tsx
  fe/src/components/myPage/MyInfo.tsx
  fe/src/pages/Mypage.tsx
Labels: Feat, FE

#99 Refactor: EditMyInfo 컴포넌트 axios적용
  fe/src/components/myPage/EditMyInfo.tsx
Labels: FE, Refactor

#100 Feat: 비밀번호 표시기능추가 및 Signup페이지 유저정보 서버전송코드 작성
  fe/public/cocktail3.ico
  fe/public/index.html
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/SignUp.tsx
Labels: Feat, FE

#102 Feat : 정규레시피 데이터 추가
  be/cocktail/src/main/java/com/BE/cocktail/controller/customeRecipe/CustomRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/controller/member/MemberController.java
  be/cocktail/src/main/java/com/BE/cocktail/controller/regularRecipe/RegularRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/apiResponse/ApiResponse.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomRecipeCreateDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomRecipeResponseDtoList.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomUpdateDto.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/customRecipe/CustomRecipe.java
  be/cocktail/src/main/java/com/BE/cocktail/service/customRecipe/CustomRecipeService.java
  be/cocktail/src/main/java/com/BE/cocktail/service/member/MemberService.java
  be/cocktail/src/main/java/com/BE/cocktail/service/regularRecipe/RegularRecipeService.java
  be/cocktail/src/main/resources/ddl/ddl.sql
  be/cocktail/src/main/resources/dml/dml.sql
Labels: BE, Feat

#103 Feat : Swagger 및 북마크 엔티티 작성
  be/cocktail/build.gradle
  be/cocktail/src/main/java/com/BE/cocktail/controller/customeRecipe/CustomRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/controller/member/MemberController.java
  be/cocktail/src/main/java/com/BE/cocktail/controller/regularRecipe/RegularRecipeController.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomRecipeGetResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeGetResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/bookmark/Bookmark.java
  be/cocktail/src/main/java/com/BE/cocktail/swagger/SwaggerConfig.java
  be/cocktail/src/main/resources/application.yml
Labels: BE, Feat

#104 Feat : 응답에 레시피 Id 추가
  be/cocktail/src/main/java/com/BE/cocktail/auth/SecurityConfig.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomRecipeGetResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomSearchResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeGetResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularSearchResponseDto.java
Labels: BE, Feat

#105 Refactor : 알코올 도수 범위 30이상으로 변경
  be/cocktail/src/main/java/com/BE/cocktail/service/regularRecipe/RegularRecipeService.java
Labels: BE, Refactor

#106 Feat : OAuth2 구글 적용
  be/cocktail/build.gradle
  be/cocktail/src/main/java/com/BE/cocktail/dto/apiResponse/CocktailRtnConsts.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/member/Member.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/member/MemberPrincipal.java
  be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/member/Role.java
  be/cocktail/src/main/java/com/BE/cocktail/security/jwt1/JwtTokenProvider.java
  be/cocktail/src/main/java/com/BE/cocktail/security/jwt1/filter/JwtAuthenticationFilter.java
  be/cocktail/src/main/java/com/BE/cocktail/security/jwt1/filter/JwtVerificationFilter.java
  be/cocktail/src/main/java/com/BE/cocktail/security/jwt1/handler/MemberAuthenticationFailureHandler.java
  be/cocktail/src/main/java/com/BE/cocktail/security/jwt1/handler/MemberAuthenticationSuccessHandler.java
  be/cocktail/src/main/java/com/BE/cocktail/security/oauth/CustomOAuth2Member.java
  be/cocktail/src/main/java/com/BE/cocktail/security/oauth/OAuthAttributes.java
  be/cocktail/src/main/java/com/BE/cocktail/security/oauth/handler/OAuth2LoginFailureHandler.java
  be/cocktail/src/main/java/com/BE/cocktail/security/oauth/handler/OAuth2LoginSuccessHandler.java
  be/cocktail/src/main/java/com/BE/cocktail/security/oauth/service/CustomOAuth2MemberService.java
  be/cocktail/src/main/java/com/BE/cocktail/security/oauth/userinfo/GoogleMemberInfo.java
  be/cocktail/src/main/java/com/BE/cocktail/security/oauth/userinfo/OAuth2MemberInfo.java
  be/cocktail/src/main/java/com/BE/cocktail/security/oauth/userinfo/ProviderType.java
  be/cocktail/src/main/java/com/BE/cocktail/service/member/MemberService.java
  be/cocktail/src/main/java/com/BE/cocktail/service/member/PrincipalDetailsService.java
  be/cocktail/src/main/java/com/BE/cocktail/utils/AuthorityUtils.java
  be/cocktail/src/main/resources/application.yml
Labels: BE, Feat

#107 Refactor : 레시피 등록 및 커스텀 훅
  fe/package.json
  fe/src/components/NavBar/NavBar.tsx
  fe/src/components/card/CardList.tsx
  fe/src/components/imageupload/ImageUpload.tsx
  fe/src/hooks/useMainPagination.ts
  fe/src/hooks/useSearchedPagination.ts
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/Main.tsx
  fe/src/pages/SearchResults.tsx
Labels: FE, Refactor

#108 Refactor: SignUp페이지 서버api 데이터 연결 및 fetch함수명 변경
  fe/src/pages/SignUp.tsx
Labels: Feat, FE, Refactor

#109 Feat : Config, dto 추가
  be/cocktail/src/main/java/com/BE/cocktail/dto/LoginResponseDto.java
  be/cocktail/src/main/java/com/BE/cocktail/security/config/SecurityConfig.java
Labels: BE, Feat

#112 Design: DetailPage 디자인수정
  fe/src/pages/DetailPage.tsx
Labels: FE, Design

#113 Feat : MyPage 버튼 기능 추가
  fe/src/components/NavBar/NavBar.tsx
  fe/src/components/card/Card.tsx
  fe/src/components/card/CardList.tsx
  fe/src/components/card/LoadingComponent.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/myPage/MenuBar.tsx
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/CustomRecipes.tsx
  fe/src/pages/Mypage.tsx
  fe/src/utils/tokeninstance.ts
Labels: Feat, FE

#114 Fix: 커스텀레시피의 정보를 조회했을때 정규레시피 정보가 보이는 버그수정
  fe/src/hooks/useFetchRecipe.tsx
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/CustomRecipes.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/Mypage.tsx
Labels: FE, Fix

#116 Fix: 커스텀레시피와 정규레시피 세부정보 데이터렌더링 표준화
  fe/src/components/myPage/MyInfo.tsx
  fe/src/hooks/useFetchRecipe.tsx
  fe/src/pages/CocktailEdit.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/Mypage.tsx
Labels: FE, Fix

#117 Feat : 레시피 삭제 기능 구현
  fe/src/components/card/RecipePagination.tsx
  fe/src/components/myPage/MyRecipes.tsx
  fe/src/hooks/useDeleteRecipe.ts
  fe/src/hooks/useFetchRecipe.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/Mypage.tsx
  fe/src/utils/query.ts
Labels: Feat, FE

#118 Refactor: Mypage 데이터 연결 및 타입, button 수정
  fe/src/components/myPage/MenuBar.tsx
  fe/src/components/myPage/MyInfo.tsx
  fe/src/pages/Mypage.tsx
Labels: FE, Refactor, Design

#119 Feat : 로그인 유도 페이지
  fe/src/components/card/SearchResultsTab.tsx
  fe/src/components/card/SearchedRecipe.tsx
  fe/src/components/errorFallback/IsNotLogin.tsx
  fe/src/images/mascot.png
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/Mypage.tsx
  fe/src/pages/SearchResults.tsx
  fe/src/pages/SignUp.tsx
  fe/src/utils/query.ts
  fe/src/utils/tokenStorege.ts
Labels: Feat, FE

#121 Feat: EditMyInfo컴포넌트 회원정보 기능 구현
  fe/src/components/myPage/EditMyInfo.tsx
  fe/src/components/myPage/MyInfo.tsx
Labels: Feat, FE, Refactor

#122 Refactor: 커스텀레시피 수정기능 수정
  fe/package.json
  fe/src/App.tsx
  fe/src/pages/CocktailEdit.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/SignUp.tsx
  fe/src/utils/query.ts
Labels: help wanted, FE, Refactor

#127 Feat : 찜 등록, 삭제, 조회 및 버그 수정
  fe/src/components/card/Card.tsx
  fe/src/components/card/CardList.tsx
  fe/src/components/imageupload/ImageUpload.tsx
  fe/src/components/loading/LoadingComponent.tsx
  fe/src/components/loginbutton/GoogleSignIn.tsx
  fe/src/components/myPage/EditMyInfo.tsx
  fe/src/components/myPage/MenuBar.tsx
  fe/src/components/myPage/MyInfo.tsx
  fe/src/components/myPage/MyRecipes.tsx
  fe/src/components/myPage/MyWishList.tsx
  fe/src/hooks/useFetchRecipe.tsx
  fe/src/hooks/useMainPagination.ts
  fe/src/pages/CocktailEdit.tsx
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/CustomRecipes.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/Mypage.tsx
  fe/src/pages/SearchResults.tsx
  fe/src/pages/SignIn.tsx
  fe/src/pages/SignUp.tsx
  fe/src/utils/query.ts
  fe/src/utils/tokeninstance.ts
Labels: Feat, FE, Refactor

#128 Feat: 빌드, 배포 완료
  fe/.gitignore
  fe/package.json
  fe/src/components/NavBar/NavBar.tsx
  fe/src/components/card/Card.tsx
  fe/src/components/card/CardList.tsx
  fe/src/components/card/RecipePagination.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/header/NavController.tsx
  fe/src/components/imageupload/ImageUpload.tsx
  fe/src/components/myPage/EditMyInfo.tsx
  fe/src/components/myPage/MyWishList.tsx
  fe/src/images/headerlogo1.png
  fe/src/pages/CocktailEdit.tsx
  fe/src/pages/CocktailRegistration.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/Mypage.tsx
  fe/src/pages/SignUp.tsx
  fe/src/utils/query.ts
  fe/src/utils/tokeninstance.ts
Labels: FE

#129 Feat: README 파일 추가
  README.md
  fe/src/images/Stackarchitecture.png
  fe/src/images/login.png
  fe/src/images/login1.png
  fe/src/images/logo-whigte.png
Labels: Feat, FE

#133 Fix : 검색 결과 페이지 검색어 변경시 페이지 번호가 초기화 되지 않는 버그
  fe/src/App.tsx
  fe/src/hooks/useSearchedPagination.ts
  fe/src/pages/SearchResults.tsx
Labels: FE, Fix

#134 Refactor : 카드 descriptoin 글자수 제한
  fe/src/components/card/Card.tsx
Labels: Refactor

#135 Refactor : NavBar 업그레이드 및 검색 결과 디자인 변경
  fe/src/components/NavBar/NavBar.tsx
  fe/src/components/card/SearchedRecipe.tsx
  fe/src/components/header/NavController.tsx
  fe/src/images/doNothaveRecipe.png
  fe/src/pages/SearchResults.tsx
  fe/src/redux/slices/NavSlice.ts
Labels: FE, Refactor
